dataset_params:
  images_path: "data/train/images"

diffusion_params:
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02

model_params:
  image_channels: 1
  image_size: 28
  down_channels: [32, 64, 128, 256]
  bottleneck_channels: [256, 256, 128]
  down_sample: [True, True, True]
  embedding_dim: 128
  num_heads: 4

train_params:
  task_name: "default"
  batch_size: 2
  num_epochs: 40
  num_samples: 100
  num_grid_rows: 10
  lr: 0.0001
  ckpt_name: "ddpm_ckpt.pth"
